// GENERATED by scripts/gen-voice.mjs — do not edit. Recorded guidance prompts per language.
// (Empty until the voices are recorded: the phone's own voice is used meanwhile.)
export const VOICE_CLIPS: Partial<Record<"ar" | "en", Record<string, any>>> = {};
